# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\_MyDocuments\__YandexDisk\Документы\___Python\Проекты\ЧПУ\cnc_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from version import get_version_app as vers


class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 550)
        MainWindow.setMinimumSize(QtCore.QSize(750, 550))
        MainWindow.setMaximumSize(QtCore.QSize(750, 562))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ico/cnc_machine.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(750, 550))
        self.centralwidget.setBaseSize(QtCore.QSize(750, 500))
        self.centralwidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.centralwidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, 9, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(750, 550))
        self.tabWidget.setBaseSize(QtCore.QSize(700, 500))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.tabWidget.setFont(font)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setWhatsThis("")
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_vik = QtWidgets.QWidget()
        self.tab_vik.setMinimumSize(QtCore.QSize(0, 0))
        self.tab_vik.setAccessibleName("")
        self.tab_vik.setAccessibleDescription("")
        self.tab_vik.setAutoFillBackground(False)
        self.tab_vik.setObjectName("tab_vik")
        self.label = QtWidgets.QLabel(self.tab_vik)
        self.label.setGeometry(QtCore.QRect(360, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab_vik)
        self.label_2.setGeometry(QtCore.QRect(500, 10, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(255, 0, 4);\n"
                                   "color: rgb(255, 255, 127);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.groupBox_ots_vik = QtWidgets.QGroupBox(self.tab_vik)
        self.groupBox_ots_vik.setGeometry(QtCore.QRect(370, 70, 321, 161))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_ots_vik.setFont(font)
        self.groupBox_ots_vik.setObjectName("groupBox_ots_vik")
        self.spinBox_ots_vik_X = QtWidgets.QSpinBox(self.groupBox_ots_vik)
        self.spinBox_ots_vik_X.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.spinBox_ots_vik_X.setMinimum(25)
        self.spinBox_ots_vik_X.setMaximum(50)
        self.spinBox_ots_vik_X.setProperty("value", 42)
        self.spinBox_ots_vik_X.setObjectName("spinBox_ots_vik_X")
        self.spinBox_ots_vik_Y = QtWidgets.QSpinBox(self.groupBox_ots_vik)
        self.spinBox_ots_vik_Y.setGeometry(QtCore.QRect(80, 60, 51, 31))
        self.spinBox_ots_vik_Y.setMinimum(25)
        self.spinBox_ots_vik_Y.setMaximum(50)
        self.spinBox_ots_vik_Y.setProperty("value", 42)
        self.spinBox_ots_vik_Y.setObjectName("spinBox_ots_vik_Y")
        self.label_ots_vik_X = QtWidgets.QLabel(self.groupBox_ots_vik)
        self.label_ots_vik_X.setGeometry(QtCore.QRect(40, 40, 21, 16))
        self.label_ots_vik_X.setObjectName("label_ots_vik_X")
        self.label_ots_vik_Y = QtWidgets.QLabel(self.groupBox_ots_vik)
        self.label_ots_vik_Y.setGeometry(QtCore.QRect(100, 40, 21, 16))
        self.label_ots_vik_Y.setObjectName("label_ots_vik_Y")
        self.btn_ots_vik_40 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_40.setGeometry(QtCore.QRect(150, 30, 75, 23))
        self.btn_ots_vik_40.setObjectName("btn_ots_vik_40")
        self.btn_ots_vik_41 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_41.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.btn_ots_vik_41.setObjectName("btn_ots_vik_41")
        self.btn_ots_vik_42 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_42.setGeometry(QtCore.QRect(150, 90, 75, 23))
        self.btn_ots_vik_42.setObjectName("btn_ots_vik_42")
        self.btn_ots_vik_43 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_43.setGeometry(QtCore.QRect(230, 30, 75, 23))
        self.btn_ots_vik_43.setObjectName("btn_ots_vik_43")
        self.btn_ots_vik_44 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_44.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.btn_ots_vik_44.setObjectName("btn_ots_vik_44")
        self.btn_ots_vik_45 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_45.setGeometry(QtCore.QRect(230, 90, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ots_vik_45.setFont(font)
        self.btn_ots_vik_45.setObjectName("btn_ots_vik_45")
        self.btn_ots_vik_46 = QtWidgets.QPushButton(self.groupBox_ots_vik)
        self.btn_ots_vik_46.setGeometry(QtCore.QRect(190, 120, 75, 23))
        self.btn_ots_vik_46.setObjectName("btn_ots_vik_46")
        self.btn_create_vik = QtWidgets.QPushButton(self.tab_vik)
        self.btn_create_vik.setGeometry(QtCore.QRect(370, 260, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_vik.setFont(font)
        self.btn_create_vik.setToolTip("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(
            "ico/Hydrattz-Multipurpose-Alphabet-Letter-V-orange.ico"),
            QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_vik.setIcon(icon1)
        self.btn_create_vik.setIconSize(QtCore.QSize(32, 32))
        self.btn_create_vik.setAutoDefault(False)
        self.btn_create_vik.setDefault(False)
        self.btn_create_vik.setFlat(False)
        self.btn_create_vik.setObjectName("btn_create_vik")
        self.tableWidget_vik = QtWidgets.QTableWidget(self.tab_vik)
        self.tableWidget_vik.setGeometry(QtCore.QRect(70, 30, 191, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_vik.setFont(font)
        self.tableWidget_vik.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_vik.setRowCount(12)
        self.tableWidget_vik.setColumnCount(2)
        self.tableWidget_vik.setObjectName("tableWidget_vik")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vik.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_vik.setHorizontalHeaderItem(1, item)
        self.tableWidget_vik.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_vik.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_vik.verticalHeader().setMinimumSectionSize(33)
        self.tabWidget.addTab(self.tab_vik, icon1, "")
        self.tab_afin = QtWidgets.QWidget()
        self.tab_afin.setObjectName("tab_afin")
        self.label_3 = QtWidgets.QLabel(self.tab_afin)
        self.label_3.setGeometry(QtCore.QRect(560, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("background-color:rgb(255, 255, 127); \n"
                                   "color: rgb(255, 0, 4);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.tab_afin)
        self.label_4.setGeometry(QtCore.QRect(420, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.groupBox_ots_afin = QtWidgets.QGroupBox(self.tab_afin)
        self.groupBox_ots_afin.setGeometry(QtCore.QRect(370, 70, 321, 161))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_ots_afin.setFont(font)
        self.groupBox_ots_afin.setObjectName("groupBox_ots_afin")
        self.spinBox_ots_afin_X = QtWidgets.QSpinBox(self.groupBox_ots_afin)
        self.spinBox_ots_afin_X.setGeometry(QtCore.QRect(20, 60, 51, 31))
        self.spinBox_ots_afin_X.setMinimum(25)
        self.spinBox_ots_afin_X.setMaximum(50)
        self.spinBox_ots_afin_X.setProperty("value", 42)
        self.spinBox_ots_afin_X.setObjectName("spinBox_ots_afin_X")
        self.spinBox_ots_afin_Y = QtWidgets.QSpinBox(self.groupBox_ots_afin)
        self.spinBox_ots_afin_Y.setGeometry(QtCore.QRect(80, 60, 51, 31))
        self.spinBox_ots_afin_Y.setMinimum(25)
        self.spinBox_ots_afin_Y.setMaximum(50)
        self.spinBox_ots_afin_Y.setProperty("value", 42)
        self.spinBox_ots_afin_Y.setObjectName("spinBox_ots_afin_Y")
        self.label_ots_afin_X = QtWidgets.QLabel(self.groupBox_ots_afin)
        self.label_ots_afin_X.setGeometry(QtCore.QRect(40, 40, 21, 16))
        self.label_ots_afin_X.setObjectName("label_ots_afin_X")
        self.label_ots_afin_Y = QtWidgets.QLabel(self.groupBox_ots_afin)
        self.label_ots_afin_Y.setGeometry(QtCore.QRect(100, 40, 21, 16))
        self.label_ots_afin_Y.setObjectName("label_ots_afin_Y")
        self.btn_ots_afin_40 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_40.setGeometry(QtCore.QRect(150, 30, 75, 23))
        self.btn_ots_afin_40.setObjectName("btn_ots_afin_40")
        self.btn_ots_afin_41 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_41.setGeometry(QtCore.QRect(150, 60, 75, 23))
        self.btn_ots_afin_41.setObjectName("btn_ots_afin_41")
        self.btn_ots_afin_42 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_42.setGeometry(QtCore.QRect(150, 90, 75, 23))
        self.btn_ots_afin_42.setObjectName("btn_ots_afin_42")
        self.btn_ots_afin_43 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_43.setGeometry(QtCore.QRect(230, 30, 75, 23))
        self.btn_ots_afin_43.setObjectName("btn_ots_afin_43")
        self.btn_ots_afin_44 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_44.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.btn_ots_afin_44.setObjectName("btn_ots_afin_44")
        self.btn_ots_afin_45 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_45.setGeometry(QtCore.QRect(230, 90, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_ots_afin_45.setFont(font)
        self.btn_ots_afin_45.setObjectName("btn_ots_afin_45")
        self.btn_ots_afin_46 = QtWidgets.QPushButton(self.groupBox_ots_afin)
        self.btn_ots_afin_46.setGeometry(QtCore.QRect(190, 120, 75, 23))
        self.btn_ots_afin_46.setObjectName("btn_ots_afin_46")
        self.btn_create_afin = QtWidgets.QPushButton(self.tab_afin)
        self.btn_create_afin.setGeometry(QtCore.QRect(370, 390, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_afin.setFont(font)
        self.btn_create_afin.setToolTip("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("ico/Icondesigner.net-Hyperion-Sidebar-Library.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_afin.setIcon(icon2)
        self.btn_create_afin.setIconSize(QtCore.QSize(32, 32))
        self.btn_create_afin.setAutoDefault(False)
        self.btn_create_afin.setDefault(False)
        self.btn_create_afin.setFlat(False)
        self.btn_create_afin.setObjectName("btn_create_afin")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_afin)
        self.groupBox_6.setGeometry(QtCore.QRect(370, 250, 161, 111))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.rBtn_afin_arc = QtWidgets.QRadioButton(self.groupBox_6)
        self.rBtn_afin_arc.setGeometry(QtCore.QRect(30, 40, 101, 17))
        self.rBtn_afin_arc.setChecked(True)
        self.rBtn_afin_arc.setObjectName("rBtn_afin_arc")
        self.rBtn_afin_pr = QtWidgets.QRadioButton(self.groupBox_6)
        self.rBtn_afin_pr.setGeometry(QtCore.QRect(30, 70, 91, 17))
        self.rBtn_afin_pr.setObjectName("rBtn_afin_pr")
        self.label_pix_afin = QtWidgets.QLabel(self.tab_afin)
        self.label_pix_afin.setGeometry(QtCore.QRect(550, 260, 140, 100))
        self.label_pix_afin.setText("")
        self.label_pix_afin.setPixmap(QtGui.QPixmap("pix/afin_arc.png"))
        self.label_pix_afin.setObjectName("label_pix_afin")
        self.tableWidget_afin = QtWidgets.QTableWidget(self.tab_afin)
        self.tableWidget_afin.setGeometry(QtCore.QRect(70, 30, 191, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_afin.setFont(font)
        self.tableWidget_afin.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_afin.setRowCount(12)
        self.tableWidget_afin.setColumnCount(2)
        self.tableWidget_afin.setObjectName("tableWidget_afin")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_afin.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_afin.setHorizontalHeaderItem(1, item)
        self.tableWidget_afin.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_afin.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_afin.verticalHeader().setMinimumSectionSize(33)
        self.tabWidget.addTab(self.tab_afin, icon2, "")
        self.tab_shit = QtWidgets.QWidget()
        self.tab_shit.setObjectName("tab_shit")
        self.label_shit = QtWidgets.QLabel(self.tab_shit)
        self.label_shit.setGeometry(QtCore.QRect(560, 10, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_shit.setFont(font)
        self.label_shit.setStyleSheet("color: rgb(170, 85, 0);")
        self.label_shit.setAlignment(QtCore.Qt.AlignCenter)
        self.label_shit.setObjectName("label_shit")
        self.tableWidget_shit = QtWidgets.QTableWidget(self.tab_shit)
        self.tableWidget_shit.setGeometry(QtCore.QRect(70, 30, 191, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_shit.setFont(font)
        self.tableWidget_shit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_shit.setRowCount(12)
        self.tableWidget_shit.setColumnCount(2)
        self.tableWidget_shit.setObjectName("tableWidget_shit")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shit.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_shit.setHorizontalHeaderItem(1, item)
        self.tableWidget_shit.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_shit.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_shit.verticalHeader().setMinimumSectionSize(33)
        self.groupBox_ots_shit = QtWidgets.QGroupBox(self.tab_shit)
        self.groupBox_ots_shit.setGeometry(QtCore.QRect(370, 70, 321, 151))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_ots_shit.setFont(font)
        self.groupBox_ots_shit.setObjectName("groupBox_ots_shit")
        self.spinBox_ots_shit_X = QtWidgets.QSpinBox(self.groupBox_ots_shit)
        self.spinBox_ots_shit_X.setGeometry(QtCore.QRect(30, 60, 51, 31))
        self.spinBox_ots_shit_X.setMinimum(25)
        self.spinBox_ots_shit_X.setMaximum(50)
        self.spinBox_ots_shit_X.setProperty("value", 42)
        self.spinBox_ots_shit_X.setObjectName("spinBox_ots_shit_X")
        self.spinBox_ots_shit_Y = QtWidgets.QSpinBox(self.groupBox_ots_shit)
        self.spinBox_ots_shit_Y.setGeometry(QtCore.QRect(90, 60, 51, 31))
        self.spinBox_ots_shit_Y.setMinimum(25)
        self.spinBox_ots_shit_Y.setMaximum(50)
        self.spinBox_ots_shit_Y.setProperty("value", 42)
        self.spinBox_ots_shit_Y.setObjectName("spinBox_ots_shit_Y")
        self.label_ots_shit_X = QtWidgets.QLabel(self.groupBox_ots_shit)
        self.label_ots_shit_X.setGeometry(QtCore.QRect(50, 40, 21, 16))
        self.label_ots_shit_X.setObjectName("label_ots_shit_X")
        self.label_ots_shit_Y = QtWidgets.QLabel(self.groupBox_ots_shit)
        self.label_ots_shit_Y.setGeometry(QtCore.QRect(110, 40, 21, 16))
        self.label_ots_shit_Y.setObjectName("label_ots_shit_Y")
        self.btn_ots_shit_42 = QtWidgets.QPushButton(self.groupBox_ots_shit)
        self.btn_ots_shit_42.setGeometry(QtCore.QRect(174, 40, 111, 81))
        self.btn_ots_shit_42.setObjectName("btn_ots_shit_42")
        self.btn_create_shit = QtWidgets.QPushButton(self.tab_shit)
        self.btn_create_shit.setGeometry(QtCore.QRect(370, 250, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_shit.setFont(font)
        self.btn_create_shit.setToolTip("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("ico/Paomedia-Small-N-Flat-Shield.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_shit.setIcon(icon3)
        self.btn_create_shit.setIconSize(QtCore.QSize(32, 32))
        self.btn_create_shit.setAutoDefault(False)
        self.btn_create_shit.setDefault(False)
        self.btn_create_shit.setFlat(False)
        self.btn_create_shit.setObjectName("btn_create_shit")
        self.tabWidget.addTab(self.tab_shit, icon3, "")
        self.tab_paz_kol = QtWidgets.QWidget()
        self.tab_paz_kol.setObjectName("tab_paz_kol")
        self.groupBox_paz = QtWidgets.QGroupBox(self.tab_paz_kol)
        self.groupBox_paz.setGeometry(QtCore.QRect(370, 70, 321, 201))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_paz.setFont(font)
        self.groupBox_paz.setObjectName("groupBox_paz")
        self.label_33 = QtWidgets.QLabel(self.groupBox_paz)
        self.label_33.setGeometry(QtCore.QRect(20, 30, 286, 153))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.btn_create_paz = QtWidgets.QPushButton(self.tab_paz_kol)
        self.btn_create_paz.setGeometry(QtCore.QRect(370, 310, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_paz.setFont(font)
        self.btn_create_paz.setToolTip("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("ico/Iconsmind-Outline-Column.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_paz.setIcon(icon4)
        self.btn_create_paz.setIconSize(QtCore.QSize(32, 32))
        self.btn_create_paz.setAutoDefault(False)
        self.btn_create_paz.setDefault(False)
        self.btn_create_paz.setFlat(False)
        self.btn_create_paz.setObjectName("btn_create_paz")
        self.tableWidget_paz = QtWidgets.QTableWidget(self.tab_paz_kol)
        self.tableWidget_paz.setGeometry(QtCore.QRect(70, 30, 191, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_paz.setFont(font)
        self.tableWidget_paz.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_paz.setRowCount(12)
        self.tableWidget_paz.setColumnCount(2)
        self.tableWidget_paz.setObjectName("tableWidget_paz")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_paz.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_paz.setHorizontalHeaderItem(1, item)
        self.tableWidget_paz.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_paz.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_paz.verticalHeader().setMinimumSectionSize(33)
        self.label_paz = QtWidgets.QLabel(self.tab_paz_kol)
        self.label_paz.setGeometry(QtCore.QRect(370, 10, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_paz.setFont(font)
        self.label_paz.setStyleSheet("color: rgb(85, 85, 255);")
        self.label_paz.setAlignment(QtCore.Qt.AlignCenter)
        self.label_paz.setObjectName("label_paz")
        self.tabWidget.addTab(self.tab_paz_kol, icon4, "")
        self.tab_paz_pr = QtWidgets.QWidget()
        self.tab_paz_pr.setObjectName("tab_paz_pr")
        self.btn_create_pazpr = QtWidgets.QPushButton(self.tab_paz_pr)
        self.btn_create_pazpr.setGeometry(QtCore.QRect(370, 260, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_create_pazpr.setFont(font)
        self.btn_create_pazpr.setToolTip("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("ico/Icons8-Ios7-Editing-Line-Width.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_create_pazpr.setIcon(icon5)
        self.btn_create_pazpr.setIconSize(QtCore.QSize(32, 32))
        self.btn_create_pazpr.setAutoDefault(False)
        self.btn_create_pazpr.setDefault(False)
        self.btn_create_pazpr.setFlat(False)
        self.btn_create_pazpr.setObjectName("btn_create_pazpr")
        self.groupBox_ots_pazpr = QtWidgets.QGroupBox(self.tab_paz_pr)
        self.groupBox_ots_pazpr.setGeometry(QtCore.QRect(370, 70, 321, 161))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.groupBox_ots_pazpr.setFont(font)
        self.groupBox_ots_pazpr.setObjectName("groupBox_ots_pazpr")
        self.spinBox_ots_pazpr_X_left = QtWidgets.QSpinBox(self.groupBox_ots_pazpr)
        self.spinBox_ots_pazpr_X_left.setGeometry(QtCore.QRect(40, 60, 51, 31))
        self.spinBox_ots_pazpr_X_left.setMinimum(0)
        self.spinBox_ots_pazpr_X_left.setMaximum(500)
        self.spinBox_ots_pazpr_X_left.setProperty("value", 30)
        self.spinBox_ots_pazpr_X_left.setObjectName("spinBox_ots_pazpr_X_left")
        self.spinBox_ots_pazpr_X_right = QtWidgets.QSpinBox(self.groupBox_ots_pazpr)
        self.spinBox_ots_pazpr_X_right.setGeometry(QtCore.QRect(110, 60, 51, 31))
        self.spinBox_ots_pazpr_X_right.setMinimum(0)
        self.spinBox_ots_pazpr_X_right.setMaximum(500)
        self.spinBox_ots_pazpr_X_right.setProperty("value", 20)
        self.spinBox_ots_pazpr_X_right.setObjectName("spinBox_ots_pazpr_X_right")
        self.label_ots_papr_X_left = QtWidgets.QLabel(self.groupBox_ots_pazpr)
        self.label_ots_papr_X_left.setGeometry(QtCore.QRect(20, 40, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ots_papr_X_left.setFont(font)
        self.label_ots_papr_X_left.setObjectName("label_ots_papr_X_left")
        self.btn_ots_papr_2030 = QtWidgets.QPushButton(self.groupBox_ots_pazpr)
        self.btn_ots_papr_2030.setGeometry(QtCore.QRect(40, 110, 121, 31))
        self.btn_ots_papr_2030.setObjectName("btn_ots_papr_2030")
        self.label_ots_pazpr_X_right = QtWidgets.QLabel(self.groupBox_ots_pazpr)
        self.label_ots_pazpr_X_right.setGeometry(QtCore.QRect(110, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_ots_pazpr_X_right.setFont(font)
        self.label_ots_pazpr_X_right.setObjectName("label_ots_pazpr_X_right")
        self.rBtn_pazpr_3paz = QtWidgets.QRadioButton(self.groupBox_ots_pazpr)
        self.rBtn_pazpr_3paz.setGeometry(QtCore.QRect(210, 80, 91, 17))
        self.rBtn_pazpr_3paz.setObjectName("rBtn_pazpr_3paz")
        self.rBtn_pazpr_2paz = QtWidgets.QRadioButton(self.groupBox_ots_pazpr)
        self.rBtn_pazpr_2paz.setGeometry(QtCore.QRect(210, 50, 101, 17))
        self.rBtn_pazpr_2paz.setChecked(True)
        self.rBtn_pazpr_2paz.setObjectName("rBtn_pazpr_2paz")
        self.rBtn_pazpr_5paz = QtWidgets.QRadioButton(self.groupBox_ots_pazpr)
        self.rBtn_pazpr_5paz.setGeometry(QtCore.QRect(210, 110, 91, 17))
        self.rBtn_pazpr_5paz.setObjectName("rBtn_pazpr_5paz")
        self.tableWidget_pazpr = QtWidgets.QTableWidget(self.tab_paz_pr)
        self.tableWidget_pazpr.setGeometry(QtCore.QRect(70, 30, 191, 421))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableWidget_pazpr.setFont(font)
        self.tableWidget_pazpr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget_pazpr.setRowCount(12)
        self.tableWidget_pazpr.setColumnCount(2)
        self.tableWidget_pazpr.setObjectName("tableWidget_pazpr")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pazpr.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_pazpr.setHorizontalHeaderItem(1, item)
        self.tableWidget_pazpr.horizontalHeader().setDefaultSectionSize(71)
        self.tableWidget_pazpr.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget_pazpr.verticalHeader().setMinimumSectionSize(33)
        self.label_pazpr = QtWidgets.QLabel(self.tab_paz_pr)
        self.label_pazpr.setGeometry(QtCore.QRect(400, 10, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_pazpr.setFont(font)
        self.label_pazpr.setStyleSheet("color: rgb(0, 0, 127);")
        self.label_pazpr.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pazpr.setObjectName("label_pazpr")
        self.tabWidget.addTab(self.tab_paz_pr, icon5, "")
        self.tab_prop = QtWidgets.QWidget()
        self.tab_prop.setObjectName("tab_prop")
        self.label_9 = QtWidgets.QLabel(self.tab_prop)
        self.label_9.setGeometry(QtCore.QRect(130, 20, 451, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.layoutWidget = QtWidgets.QWidget(self.tab_prop)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 90, 691, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.spinBox_prop_is_X = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_prop_is_X.setGeometry(QtCore.QRect(90, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_is_X.setFont(font)
        self.spinBox_prop_is_X.setMaximum(2000)
        self.spinBox_prop_is_X.setObjectName("spinBox_prop_is_X")
        self.label_24 = QtWidgets.QLabel(self.groupBox_3)
        self.label_24.setGeometry(QtCore.QRect(60, 110, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.spinBox_prop_is_Z = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_prop_is_Z.setGeometry(QtCore.QRect(90, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_is_Z.setFont(font)
        self.spinBox_prop_is_Z.setObjectName("spinBox_prop_is_Z")
        self.label_25 = QtWidgets.QLabel(self.groupBox_3)
        self.label_25.setGeometry(QtCore.QRect(60, 70, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_3)
        self.label_26.setGeometry(QtCore.QRect(60, 30, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.spinBox_prop_is_Y = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox_prop_is_Y.setGeometry(QtCore.QRect(90, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_is_Y.setFont(font)
        self.spinBox_prop_is_Y.setMaximum(2000)
        self.spinBox_prop_is_Y.setObjectName("spinBox_prop_is_Y")
        self.btn_prop = QtWidgets.QPushButton(self.groupBox_3)
        self.btn_prop.setGeometry(QtCore.QRect(60, 160, 111, 31))
        self.btn_prop.setObjectName("btn_prop")
        self.horizontalLayout.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.spinBox_prop_ras_X = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_prop_ras_X.setGeometry(QtCore.QRect(90, 30, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_ras_X.setFont(font)
        self.spinBox_prop_ras_X.setMaximum(2000)
        self.spinBox_prop_ras_X.setObjectName("spinBox_prop_ras_X")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(60, 70, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(60, 30, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(60, 110, 16, 20))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.spinBox_prop_ras_Y = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_prop_ras_Y.setGeometry(QtCore.QRect(90, 70, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_ras_Y.setFont(font)
        self.spinBox_prop_ras_Y.setMaximum(2000)
        self.spinBox_prop_ras_Y.setObjectName("spinBox_prop_ras_Y")
        self.spinBox_prop_ras_Z = QtWidgets.QSpinBox(self.groupBox_4)
        self.spinBox_prop_ras_Z.setGeometry(QtCore.QRect(90, 110, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spinBox_prop_ras_Z.setFont(font)
        self.spinBox_prop_ras_Z.setObjectName("spinBox_prop_ras_Z")
        self.horizontalLayout.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_10 = QtWidgets.QLabel(self.groupBox_5)
        self.label_10.setGeometry(QtCore.QRect(80, 20, 81, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_5)
        self.label_11.setGeometry(QtCore.QRect(30, 40, 61, 20))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_5)
        self.label_12.setGeometry(QtCore.QRect(140, 40, 61, 20))
        self.label_12.setObjectName("label_12")
        self.spinBox_prop_zag_X = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_prop_zag_X.setGeometry(QtCore.QRect(30, 60, 42, 22))
        self.spinBox_prop_zag_X.setObjectName("spinBox_prop_zag_X")
        self.spinBox_prop_zag_Y = QtWidgets.QSpinBox(self.groupBox_5)
        self.spinBox_prop_zag_Y.setGeometry(QtCore.QRect(140, 60, 42, 22))
        self.spinBox_prop_zag_Y.setObjectName("spinBox_prop_zag_Y")
        self.label_13 = QtWidgets.QLabel(self.groupBox_5)
        self.label_13.setGeometry(QtCore.QRect(80, 110, 91, 20))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_5)
        self.label_14.setGeometry(QtCore.QRect(50, 130, 16, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_5)
        self.label_15.setGeometry(QtCore.QRect(100, 130, 16, 20))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_5)
        self.label_16.setGeometry(QtCore.QRect(170, 130, 20, 20))
        self.label_16.setObjectName("label_16")
        self.lineEdit_zag_Y = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_zag_Y.setGeometry(QtCore.QRect(90, 150, 51, 20))
        self.lineEdit_zag_Y.setObjectName("lineEdit_zag_Y")
        self.lineEdit_zag_Z = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_zag_Z.setGeometry(QtCore.QRect(160, 150, 51, 20))
        self.lineEdit_zag_Z.setObjectName("lineEdit_zag_Z")
        self.lineEdit_zag_X = QtWidgets.QLineEdit(self.groupBox_5)
        self.lineEdit_zag_X.setGeometry(QtCore.QRect(20, 150, 51, 20))
        self.lineEdit_zag_X.setObjectName("lineEdit_zag_X")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(80, 150, 16, 20))
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.groupBox_5)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("ico/Icons8-Windows-8-Science-Geometry.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_prop, icon6, "")
        self.tab_setting = QtWidgets.QWidget()
        self.tab_setting.setObjectName("tab_setting")
        self.toolBox_setting = QtWidgets.QToolBox(self.tab_setting)
        self.toolBox_setting.setGeometry(QtCore.QRect(18, 72, 691, 401))
        self.toolBox_setting.setObjectName("toolBox_setting")
        self.page_shields = QtWidgets.QWidget()
        self.page_shields.setGeometry(QtCore.QRect(0, 0, 691, 281))
        self.page_shields.setObjectName("page_shields")
        self.groupBox_7 = QtWidgets.QGroupBox(self.page_shields)
        self.groupBox_7.setGeometry(QtCore.QRect(20, 100, 291, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_7.setObjectName("groupBox_7")
        self.lineEdit_shield_template = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_shield_template.setGeometry(QtCore.QRect(80, 40, 181, 20))
        self.lineEdit_shield_template.setObjectName("lineEdit_shield_template")
        self.toolButton_select_shield_template = QtWidgets.QToolButton(self.groupBox_7)
        self.toolButton_select_shield_template.setGeometry(QtCore.QRect(30, 40, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_shield_template.setFont(font)
        self.toolButton_select_shield_template.setObjectName("toolButton_select_shield_template")
        self.groupBox_8 = QtWidgets.QGroupBox(self.page_shields)
        self.groupBox_8.setGeometry(QtCore.QRect(380, 100, 291, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_8.setObjectName("groupBox_8")
        self.lineEdit_shield_prefix = QtWidgets.QLineEdit(self.groupBox_8)
        self.lineEdit_shield_prefix.setGeometry(QtCore.QRect(110, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_shield_prefix.setFont(font)
        self.lineEdit_shield_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_shield_prefix.setObjectName("lineEdit_shield_prefix")
        self.toolBox_setting.addItem(self.page_shields, icon3, "")
        self.page_paz = QtWidgets.QWidget()
        self.page_paz.setGeometry(QtCore.QRect(0, 0, 691, 281))
        self.page_paz.setObjectName("page_paz")
        self.groupBox_9 = QtWidgets.QGroupBox(self.page_paz)
        self.groupBox_9.setGeometry(QtCore.QRect(20, 30, 651, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_9.setObjectName("groupBox_9")
        self.lineEdit_paz2_template = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_paz2_template.setGeometry(QtCore.QRect(230, 60, 131, 20))
        self.lineEdit_paz2_template.setObjectName("lineEdit_paz2_template")
        self.toolButton_select_paz2_template = QtWidgets.QToolButton(self.groupBox_9)
        self.toolButton_select_paz2_template.setGeometry(QtCore.QRect(180, 60, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_paz2_template.setFont(font)
        self.toolButton_select_paz2_template.setObjectName("toolButton_select_paz2_template")
        self.lineEdit_paz2_prefix = QtWidgets.QLineEdit(self.groupBox_9)
        self.lineEdit_paz2_prefix.setGeometry(QtCore.QRect(490, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_paz2_prefix.setFont(font)
        self.lineEdit_paz2_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_paz2_prefix.setObjectName("lineEdit_paz2_prefix")
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setGeometry(QtCore.QRect(230, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_18 = QtWidgets.QLabel(self.groupBox_9)
        self.label_18.setGeometry(QtCore.QRect(500, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.line = QtWidgets.QFrame(self.groupBox_9)
        self.line.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.groupBox_9)
        self.line_2.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.groupBox_10 = QtWidgets.QGroupBox(self.page_paz)
        self.groupBox_10.setGeometry(QtCore.QRect(20, 150, 651, 101))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_10.setObjectName("groupBox_10")
        self.lineEdit_paz3_template = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_paz3_template.setGeometry(QtCore.QRect(230, 60, 131, 20))
        self.lineEdit_paz3_template.setObjectName("lineEdit_paz3_template")
        self.toolButton_select_paz3_template = QtWidgets.QToolButton(self.groupBox_10)
        self.toolButton_select_paz3_template.setGeometry(QtCore.QRect(180, 60, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_paz3_template.setFont(font)
        self.toolButton_select_paz3_template.setObjectName("toolButton_select_paz3_template")
        self.lineEdit_paz3_prefix = QtWidgets.QLineEdit(self.groupBox_10)
        self.lineEdit_paz3_prefix.setGeometry(QtCore.QRect(490, 50, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_paz3_prefix.setFont(font)
        self.lineEdit_paz3_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_paz3_prefix.setObjectName("lineEdit_paz3_prefix")
        self.label_19 = QtWidgets.QLabel(self.groupBox_10)
        self.label_19.setGeometry(QtCore.QRect(230, 40, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_10)
        self.label_20.setGeometry(QtCore.QRect(500, 30, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.line_3 = QtWidgets.QFrame(self.groupBox_10)
        self.line_3.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(self.groupBox_10)
        self.line_4.setGeometry(QtCore.QRect(30, 48, 61, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(self.groupBox_10)
        self.line_5.setGeometry(QtCore.QRect(20, 70, 81, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.toolBox_setting.addItem(self.page_paz, icon4, "")
        self.page_pazpr = QtWidgets.QWidget()
        self.page_pazpr.setGeometry(QtCore.QRect(0, 0, 691, 281))
        self.page_pazpr.setObjectName("page_pazpr")
        self.groupBox_11 = QtWidgets.QGroupBox(self.page_pazpr)
        self.groupBox_11.setGeometry(QtCore.QRect(20, 10, 651, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_11.setObjectName("groupBox_11")
        self.lineEdit_pazpr2_template = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_pazpr2_template.setGeometry(QtCore.QRect(230, 40, 131, 20))
        self.lineEdit_pazpr2_template.setObjectName("lineEdit_pazpr2_template")
        self.toolButton_select_pazpr2_template = QtWidgets.QToolButton(self.groupBox_11)
        self.toolButton_select_pazpr2_template.setGeometry(QtCore.QRect(180, 40, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_pazpr2_template.setFont(font)
        self.toolButton_select_pazpr2_template.setObjectName("toolButton_select_pazpr2_template")
        self.lineEdit_pazpr2_prefix = QtWidgets.QLineEdit(self.groupBox_11)
        self.lineEdit_pazpr2_prefix.setGeometry(QtCore.QRect(490, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_pazpr2_prefix.setFont(font)
        self.lineEdit_pazpr2_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pazpr2_prefix.setObjectName("lineEdit_pazpr2_prefix")
        self.label_27 = QtWidgets.QLabel(self.groupBox_11)
        self.label_27.setGeometry(QtCore.QRect(230, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.groupBox_11)
        self.label_28.setGeometry(QtCore.QRect(500, 10, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.line_6 = QtWidgets.QFrame(self.groupBox_11)
        self.line_6.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(self.groupBox_11)
        self.line_7.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.groupBox_12 = QtWidgets.QGroupBox(self.page_pazpr)
        self.groupBox_12.setGeometry(QtCore.QRect(20, 100, 651, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_12.setObjectName("groupBox_12")
        self.lineEdit_pazpr3_template = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_pazpr3_template.setGeometry(QtCore.QRect(230, 40, 131, 20))
        self.lineEdit_pazpr3_template.setObjectName("lineEdit_pazpr3_template")
        self.toolButton_select_pazpr3_template = QtWidgets.QToolButton(self.groupBox_12)
        self.toolButton_select_pazpr3_template.setGeometry(QtCore.QRect(180, 40, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_pazpr3_template.setFont(font)
        self.toolButton_select_pazpr3_template.setObjectName("toolButton_select_pazpr3_template")
        self.lineEdit_pazpr3_prefix = QtWidgets.QLineEdit(self.groupBox_12)
        self.lineEdit_pazpr3_prefix.setGeometry(QtCore.QRect(490, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_pazpr3_prefix.setFont(font)
        self.lineEdit_pazpr3_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pazpr3_prefix.setObjectName("lineEdit_pazpr3_prefix")
        self.label_29 = QtWidgets.QLabel(self.groupBox_12)
        self.label_29.setGeometry(QtCore.QRect(230, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.groupBox_12)
        self.label_30.setGeometry(QtCore.QRect(500, 10, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.line_8 = QtWidgets.QFrame(self.groupBox_12)
        self.line_8.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(self.groupBox_12)
        self.line_9.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_12 = QtWidgets.QFrame(self.groupBox_12)
        self.line_12.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.groupBox_13 = QtWidgets.QGroupBox(self.page_pazpr)
        self.groupBox_13.setGeometry(QtCore.QRect(20, 190, 651, 81))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_13.setObjectName("groupBox_13")
        self.lineEdit_pazpr5_template = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_pazpr5_template.setGeometry(QtCore.QRect(230, 40, 131, 20))
        self.lineEdit_pazpr5_template.setObjectName("lineEdit_pazpr5_template")
        self.toolButton_select_pazpr5_template = QtWidgets.QToolButton(self.groupBox_13)
        self.toolButton_select_pazpr5_template.setGeometry(QtCore.QRect(180, 40, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_pazpr5_template.setFont(font)
        self.toolButton_select_pazpr5_template.setObjectName("toolButton_select_pazpr5_template")
        self.lineEdit_pazpr5_prefix = QtWidgets.QLineEdit(self.groupBox_13)
        self.lineEdit_pazpr5_prefix.setGeometry(QtCore.QRect(490, 30, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_pazpr5_prefix.setFont(font)
        self.lineEdit_pazpr5_prefix.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_pazpr5_prefix.setObjectName("lineEdit_pazpr5_prefix")
        self.label_31 = QtWidgets.QLabel(self.groupBox_13)
        self.label_31.setGeometry(QtCore.QRect(230, 20, 121, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.groupBox_13)
        self.label_32.setGeometry(QtCore.QRect(500, 10, 61, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.line_10 = QtWidgets.QFrame(self.groupBox_13)
        self.line_10.setGeometry(QtCore.QRect(20, 50, 81, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_13 = QtWidgets.QFrame(self.groupBox_13)
        self.line_13.setGeometry(QtCore.QRect(20, 40, 81, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_11 = QtWidgets.QFrame(self.groupBox_13)
        self.line_11.setGeometry(QtCore.QRect(20, 30, 81, 16))
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_14 = QtWidgets.QFrame(self.groupBox_13)
        self.line_14.setGeometry(QtCore.QRect(20, 20, 81, 16))
        self.line_14.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(self.groupBox_13)
        self.line_15.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.line_15.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.toolBox_setting.addItem(self.page_pazpr, icon5, "")
        self.page_main_settings = QtWidgets.QWidget()
        self.page_main_settings.setGeometry(QtCore.QRect(0, 0, 691, 281))
        self.page_main_settings.setObjectName("page_main_settings")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_main_settings)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 10, 651, 111))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_setting_mainfolder = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_setting_mainfolder.setGeometry(QtCore.QRect(90, 30, 531, 20))
        self.lineEdit_setting_mainfolder.setObjectName("lineEdit_setting_mainfolder")
        self.toolButton_select_mainfolder = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_select_mainfolder.setGeometry(QtCore.QRect(30, 30, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_mainfolder.setFont(font)
        self.toolButton_select_mainfolder.setObjectName("toolButton_select_mainfolder")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 60, 601, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 80, 601, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.groupBox = QtWidgets.QGroupBox(self.page_main_settings)
        self.groupBox.setGeometry(QtCore.QRect(20, 140, 651, 91))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setToolTip("")
        self.groupBox.setStatusTip("")
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setFlat(False)
        self.groupBox.setObjectName("groupBox")
        self.lineEdit_setting_templatefolder = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_setting_templatefolder.setGeometry(QtCore.QRect(90, 30, 531, 20))
        self.lineEdit_setting_templatefolder.setObjectName("lineEdit_setting_templatefolder")
        self.toolButton_select_templatefolder = QtWidgets.QToolButton(self.groupBox)
        self.toolButton_select_templatefolder.setGeometry(QtCore.QRect(30, 30, 31, 19))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.toolButton_select_templatefolder.setFont(font)
        self.toolButton_select_templatefolder.setObjectName("toolButton_select_templatefolder")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(70, 60, 601, 16))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.checkBox_setting_cleancomments = QtWidgets.QCheckBox(self.page_main_settings)
        self.checkBox_setting_cleancomments.setGeometry(QtCore.QRect(70, 240, 541, 41))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_setting_cleancomments.setFont(font)
        self.checkBox_setting_cleancomments.setIconSize(QtCore.QSize(16, 16))
        self.checkBox_setting_cleancomments.setCheckable(True)
        self.checkBox_setting_cleancomments.setChecked(True)
        self.checkBox_setting_cleancomments.setObjectName("checkBox_setting_cleancomments")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("ico/application_x_desktop.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolBox_setting.addItem(self.page_main_settings, icon7, "")
        self.frame = QtWidgets.QFrame(self.tab_setting)
        self.frame.setGeometry(QtCore.QRect(0, 60, 731, 431))
        self.frame.setStyleSheet("background-color: rgb(240, 240, 240);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_save_setting = QtWidgets.QPushButton(self.tab_setting)
        self.btn_save_setting.setGeometry(QtCore.QRect(510, 10, 201, 41))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("ico/Hopstarter-Rounded-Square-Button-Ok.ico"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save_setting.setIcon(icon8)
        self.btn_save_setting.setIconSize(QtCore.QSize(25, 25))
        self.btn_save_setting.setAutoDefault(False)
        self.btn_save_setting.setDefault(False)
        self.btn_save_setting.setFlat(False)
        self.btn_save_setting.setObjectName("btn_save_setting")
        self.label_34 = QtWidgets.QLabel(self.tab_setting)
        self.label_34.setGeometry(QtCore.QRect(20, 20, 21, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_version = QtWidgets.QLabel(self.tab_setting)
        self.label_version.setGeometry(QtCore.QRect(34, 18, 71, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(170, 0, 0);")
        self.label_version.setObjectName("label_version")
        self.frame.raise_()
        self.toolBox_setting.raise_()
        self.btn_save_setting.raise_()
        self.label_34.raise_()
        self.label_version.raise_()
        self.tabWidget.addTab(self.tab_setting, icon7, "")
        self.horizontalLayout_2.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(6)
        self.toolBox_setting.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate(
            "MainWindow", "Создатель ЧПУ программ (АртФасадЮг) - v." + vers()))
        self.label.setText(_translate("MainWindow", "филёнки"))
        self.label_2.setText(_translate("MainWindow", "ВИКТОРИЯ"))
        self.groupBox_ots_vik.setTitle(_translate("MainWindow", "Отступ"))
        self.label_ots_vik_X.setText(_translate("MainWindow", "X"))
        self.label_ots_vik_Y.setText(_translate("MainWindow", "Y"))
        self.btn_ots_vik_40.setText(_translate("MainWindow", "40m"))
        self.btn_ots_vik_41.setText(_translate("MainWindow", "41e"))
        self.btn_ots_vik_42.setText(_translate("MainWindow", "42"))
        self.btn_ots_vik_43.setText(_translate("MainWindow", "43t"))
        self.btn_ots_vik_44.setText(_translate("MainWindow", "44c"))
        self.btn_ots_vik_45.setText(_translate("MainWindow", "45p"))
        self.btn_ots_vik_46.setText(_translate("MainWindow", "46s"))
        self.btn_create_vik.setText(_translate("MainWindow", "Создать программы"))
        item = self.tableWidget_vik.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_vik.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_vik),
                                  _translate("MainWindow", "Виктория (ф)"))
        self.label_3.setText(_translate("MainWindow", "АФИНЫ"))
        self.label_4.setText(_translate("MainWindow", "филёнки"))
        self.groupBox_ots_afin.setTitle(_translate("MainWindow", "Отступ"))
        self.label_ots_afin_X.setText(_translate("MainWindow", "X"))
        self.label_ots_afin_Y.setText(_translate("MainWindow", "Y"))
        self.btn_ots_afin_40.setText(_translate("MainWindow", "40m"))
        self.btn_ots_afin_41.setText(_translate("MainWindow", "41e"))
        self.btn_ots_afin_42.setText(_translate("MainWindow", "42"))
        self.btn_ots_afin_43.setText(_translate("MainWindow", "43t"))
        self.btn_ots_afin_44.setText(_translate("MainWindow", "44c"))
        self.btn_ots_afin_45.setText(_translate("MainWindow", "45p"))
        self.btn_ots_afin_46.setText(_translate("MainWindow", "46s"))
        self.btn_create_afin.setText(_translate("MainWindow", "Создать программы"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Стиль"))
        self.rBtn_afin_arc.setText(_translate("MainWindow", "с Арками"))
        self.rBtn_afin_pr.setText(_translate("MainWindow", "прямые"))
        item = self.tableWidget_afin.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_afin.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_afin),
                                  _translate("MainWindow", "Афины (ф)"))
        self.label_shit.setText(_translate("MainWindow", "Щиты"))
        item = self.tableWidget_shit.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_shit.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.groupBox_ots_shit.setTitle(_translate("MainWindow", "Отступ"))
        self.label_ots_shit_X.setText(_translate("MainWindow", "X"))
        self.label_ots_shit_Y.setText(_translate("MainWindow", "Y"))
        self.btn_ots_shit_42.setText(_translate("MainWindow", "Стандарт\n"
                                                "42"))
        self.btn_create_shit.setText(_translate("MainWindow", "Создать программы"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.tab_shit), _translate("MainWindow", "Щиты"))
        self.groupBox_paz.setTitle(_translate("MainWindow", "Примечание"))
        self.label_33.setText(_translate(
            "MainWindow", "<html><head/><body><p>Если размер Y-ка меньше или равен</p><p>62мм, то делаются программы на</p><p>2 паза (под узкие колонны).</p><p>Во всех остальных случаях</p><p>делаются программы на 3 паза </p></body></html>"))
        self.btn_create_paz.setText(_translate("MainWindow", "Создать программы"))
        item = self.tableWidget_paz.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_paz.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.label_paz.setText(_translate("MainWindow", "Пазы (для колонн)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paz_kol),
                                  _translate("MainWindow", "Пазы (колонны)"))
        self.btn_create_pazpr.setText(_translate("MainWindow", "Создать программы"))
        self.groupBox_ots_pazpr.setTitle(_translate("MainWindow", "Отступ"))
        self.label_ots_papr_X_left.setText(_translate("MainWindow", "<-- X слева"))
        self.btn_ots_papr_2030.setToolTip(_translate(
            "MainWindow", "<html><head/><body><p>Идеально для колонн у которых с одной стороны колёвка, а с другой стороны просто обрезано прямо.</p></body></html>"))
        self.btn_ots_papr_2030.setText(_translate("MainWindow", "30 / 20"))
        self.label_ots_pazpr_X_right.setText(_translate("MainWindow", "X справа -->"))
        self.rBtn_pazpr_3paz.setText(_translate("MainWindow", "3 паза"))
        self.rBtn_pazpr_2paz.setText(_translate("MainWindow", "2 паза"))
        self.rBtn_pazpr_5paz.setText(_translate("MainWindow", "5 пазов"))
        item = self.tableWidget_pazpr.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "X"))
        item = self.tableWidget_pazpr.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Y"))
        self.label_pazpr.setText(_translate("MainWindow", "Пазы (прямые)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paz_pr),
                                  _translate("MainWindow", "Пазы прямые"))
        self.label_9.setText(_translate("MainWindow", "Быстрый просчёт пропорций"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Исходные размеры заготовки"))
        self.label_24.setText(_translate("MainWindow", "Z"))
        self.label_25.setText(_translate("MainWindow", "Y"))
        self.label_26.setText(_translate("MainWindow", "X "))
        self.btn_prop.setText(_translate("MainWindow", "Рассчитать"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Расчитанные пропорции"))
        self.label_21.setText(_translate("MainWindow", "Y"))
        self.label_22.setText(_translate("MainWindow", "X "))
        self.label_23.setText(_translate("MainWindow", "Z"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Размеры заготовки"))
        self.label_10.setText(_translate("MainWindow", "Добавление"))
        self.label_11.setText(_translate("MainWindow", "по X (в мм)"))
        self.label_12.setText(_translate("MainWindow", "по Y (в мм)"))
        self.spinBox_prop_zag_X.setSpecialValueText(_translate("MainWindow", "20"))
        self.spinBox_prop_zag_Y.setSpecialValueText(_translate("MainWindow", "20"))
        self.label_13.setText(_translate("MainWindow", "Заготовка (в мм)"))
        self.label_14.setText(_translate("MainWindow", "X "))
        self.label_15.setText(_translate("MainWindow", "Y"))
        self.label_16.setText(_translate("MainWindow", "Z"))
        self.label_17.setText(_translate("MainWindow", "x"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_prop),
                                  _translate("MainWindow", "Пропорции"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Шаблон для создания программ Щитов"))
        self.lineEdit_shield_template.setText(_translate("MainWindow", "shitok-chis"))
        self.toolButton_select_shield_template.setText(_translate("MainWindow", "..."))
        self.groupBox_8.setTitle(_translate("MainWindow", "Префикс для названий программ Щитов"))
        self.lineEdit_shield_prefix.setText(_translate("MainWindow", "sh"))
        self.toolBox_setting.setItemText(self.toolBox_setting.indexOf(
            self.page_shields), _translate("MainWindow", "Настройки для вкладки Щиты"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Под 2 полосы"))
        self.lineEdit_paz2_template.setText(_translate("MainWindow", "paz2c"))
        self.toolButton_select_paz2_template.setText(_translate("MainWindow", "..."))
        self.lineEdit_paz2_prefix.setText(_translate("MainWindow", "2p"))
        self.label_5.setText(_translate("MainWindow", "Название шаблона"))
        self.label_18.setText(_translate("MainWindow", "Префикс"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Под 3 полосы"))
        self.lineEdit_paz3_template.setText(_translate("MainWindow", "paz3c"))
        self.toolButton_select_paz3_template.setText(_translate("MainWindow", "..."))
        self.lineEdit_paz3_prefix.setText(_translate("MainWindow", "3p"))
        self.label_19.setText(_translate("MainWindow", "Название шаблона"))
        self.label_20.setText(_translate("MainWindow", "Префикс"))
        self.toolBox_setting.setItemText(self.toolBox_setting.indexOf(
            self.page_paz), _translate("MainWindow", "Настройки для вкладки Пазы (колонны)"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Под 2 полосы (прямые)"))
        self.lineEdit_pazpr2_template.setText(_translate("MainWindow", "paz2s"))
        self.toolButton_select_pazpr2_template.setText(_translate("MainWindow", "..."))
        self.lineEdit_pazpr2_prefix.setText(_translate("MainWindow", "2s"))
        self.label_27.setText(_translate("MainWindow", "Название шаблона"))
        self.label_28.setText(_translate("MainWindow", "Префикс"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Под 3 полосы (прямые)"))
        self.lineEdit_pazpr3_template.setText(_translate("MainWindow", "paz3s"))
        self.toolButton_select_pazpr3_template.setText(_translate("MainWindow", "..."))
        self.lineEdit_pazpr3_prefix.setText(_translate("MainWindow", "3s"))
        self.label_29.setText(_translate("MainWindow", "Название шаблона"))
        self.label_30.setText(_translate("MainWindow", "Префикс"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Под 5 полос (прямые)"))
        self.lineEdit_pazpr5_template.setText(_translate("MainWindow", "paz5s"))
        self.toolButton_select_pazpr5_template.setText(_translate("MainWindow", "..."))
        self.lineEdit_pazpr5_prefix.setText(_translate("MainWindow", "5s"))
        self.label_31.setText(_translate("MainWindow", "Название шаблона"))
        self.label_32.setText(_translate("MainWindow", "Префикс"))
        self.toolBox_setting.setItemText(self.toolBox_setting.indexOf(
            self.page_pazpr), _translate("MainWindow", "Настройки для вкладки Пазы прямые"))
        self.groupBox_2.setTitle(_translate(
            "MainWindow", "Выходная КОРНЕВАЯ папка с готовыми программами"))
        self.toolButton_select_mainfolder.setToolTip(_translate(
            "MainWindow", "Этой кнопкой можно выбрать необходимую папку"))
        self.toolButton_select_mainfolder.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate(
            "MainWindow", "      Папка, в которой находятся другие подпапки (типа \'на 41 Виктория\' или \'на 43 Афина\') и уже в этих подпапках"))
        self.label_8.setText(_translate("MainWindow", "будут лежать готовые программы."))
        self.groupBox.setTitle(_translate(
            "MainWindow", "Папка с шаблонами (для выбора впишите в поле путь к папке или нажмите кнопку выбора)"))
        self.toolButton_select_templatefolder.setToolTip(_translate(
            "MainWindow", "Этой кнопкой можно выбрать необходимую папку"))
        self.toolButton_select_templatefolder.setText(_translate("MainWindow", "..."))
        self.label_6.setText(_translate(
            "MainWindow", "Это папка, где лежат файлы шаблонов с расширением shb."))
        self.checkBox_setting_cleancomments.setText(_translate(
            "MainWindow", "Очищать готовые программы от комментариев в скобках, если такие комментарии есть в шаблонах"))
        self.toolBox_setting.setItemText(self.toolBox_setting.indexOf(
            self.page_main_settings), _translate("MainWindow", "Гланые Настройки"))
        self.btn_save_setting.setToolTip(_translate(
            "MainWindow", "Обязательно нажимайте эту кнопку после внесения изменений в настройки"))
        self.btn_save_setting.setText(_translate("MainWindow", "Сохранить изменения"))
        self.label_34.setText(_translate("MainWindow", "v."))
        self.label_version.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setting),
                                  _translate("MainWindow", "Настройки"))
